### ISSUE TITLE
Go와 struct 포인터에 대한 질문

### ISSUE THREAD

**Issue by json9512** [json9512/mediumclone-backendwithgo#31]
최근 어떤 Medium 글을 읽었음. [Understanding allocations in Go](https://medium.com/eureka-engineering/understanding-allocations-in-go-stack-heap-memory-9a2631b5035d), [Bad go: pointer returns](https://philpearl.github.io/post/bad_go_pointer_returns/)

이 글에 따르면 pointer를 사용 할 때 bottom-up 방식으로 하게되면 heap allocation이 생기지만 top-down 방식으로 reference 할 때는 heap allocation이 생기지 않음 (무조건적인 것은 아님). 

```golang
// Top-down 방식
func main() {
    y := 2
    _ = doSomething(&y)
}

func doSomething(y *int) int {
    x := *y * 2
    return x
}
// heap allocation이 발생하지 않음
```
```golang
// bottom-up 방식
func main() {
    _ = doSomething()
}

func doSomething() *int {
    y := 2
    x := y * 2
    return &x
}
// heap allocation이 발생함
// x는 heap memory에 저장됨
```

비슷한 맥락으로 `struct`을 사용할 때 아래와 같다고 생각을 해보자.
```golang
type Message struct {
    sender, recipient, content string
}

func createMessage(sender, recipient, content string) Message {
    return Message{
        sender: sender,
        recipient: recipient,
        content: content,
    }
}

func createMessageHeapAllocation(sender, recipient, content string) *Message {
    return &Message{
        sender: sender,
        recipient: recipient,
        content: content,
    }
}
```
여기서 `createMessage`는 heap allocation이 발생하지 않지만 `createMessageHeapAllocation`은 heap allocation이 발생함.

```golang
func testCreateMessage() {
    for i := 0; i < 20000000; i++ {
        _ = createMessage("Tom', "Mike", "Hello")
    }
}

func testCreateMessageHeapAllocation() {
    for i := 0; i < 20000000; i++ {
        _ = createMessageHeapAllocation("Tom', "Mike", "Hello")
    }
}
```
이렇게 극단적으로 테스트를 한다고 가정하면 `testCreateMessageHeapAllocation` 가 `testCreateMessage` 보다 느림. (heap memory에 연관된 기능들이 overhead를 발생시킴. ex. GC cycle)

근데 `CreateMessageHeapAllocation` 처럼 특정 `struct`의 포인터를 리턴하는 함수는 다른 Go repo를 보다보면 종종 볼 수 있음. 

****

여기서 질문. 
1. `struct`의 포인터를 리턴하는 이유?  (디자인 패턴 때문인가?)
2. 포인터를 리턴하는 것이 성능면에서 비효율적인데 `struct`을 그냥 리턴해도 되는 것인지? (ex. `CreateMessage` 함수)
3. 앱은 비효율적이라도 컴퓨팅 파워가 좋아서 신경을 안쓰는 것인지, 아니면 혼자 개발하는 것이 아니니까 협업을 위해서인지?
4. 진리의 케바케인지?

**Comment by dojinkimm** [comment]
1. 포인터로 계속 사용하고 싶은 경우가 있으니 주소를 리턴하는 것. 리턴된 주소의 값을 계속 바꾼다던지 등등.
2. 크게 상관은 없을듯. 근데 굳이 상관없다면 통일된 스타일로 하는게 좋을듯. 
3. 이런 작은 차이들이 웹앱 어플리케이션에서는 속도에 크리티컬 하지 않으니 신경안쓰는 부분도 있는듯?? heap 조금 쓴다고 속도가 크게 저하되지 않으니

https://stackoverflow.com/questions/23542989/pointers-vs-values-in-parameters-and-return-values 요 stackoverflow가 괜춘하게 답해줌

> Methods using receiver pointers are common; the rule of thumb for receivers is, "If in doubt, use a pointer."

**Comment by json9512** [comment]
더 찾아보니:
- `struct`이 크고 life cycle이 긴 경우는 포인터를 리턴하는 것이 훨씬 메모리 효율이 좋음
